export const ADD_IDEA = 'ADD_IDEA';
export const ADD_SORTED_IDEAS = 'ADD_SORTED_IDEAS';
export const ADD_LIKED_IDEAS = 'ADD_LIKED_IDEAS';
export const ADD_FLAGGED_IDEAS = 'ADD_FLAGGED_IDEAS';
export const REMOVE_LIKED_IDEA = 'REMOVE_LIKED_IDEA';
export const REMOVE_FLAGGED_IDEA = 'REMOVE_FLAGGED_IDEA';
export const REMOVE_LIKED_AND_FLAGGED_IDEAS = 'REMOVE_LIKED_AND_FLAGGED_IDEAS';
export const IDEAS_LOADING = 'IDEAS_LOADING';
export const IDEAS_FAILED = 'IDEAS_FAILED';

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

