export const ADD_IDEA = 'ADD_IDEA';
export const ADD_SORTED_IDEAS = 'ADD_SORTED_IDEAS';
export const LIKE_IDEAS = 'LIKE_IDEAS';
export const FLAG_IDEAS = 'FLAG_IDEAS';
export const IDEAS_LOADING = 'IDEAS_LOADING';
export const IDEAS_FAILED = 'IDEAS_FAILED';


// BELOW NOT YET IMPLEMENTED...

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';


